### ISSUE TITLE
CookieBuilder.withMaxAgeInSeconds(long) add 'maxAge=' to cookie instead of 'Max-Age='

### ISSUE THREAD

**Issue by Przemek0** [3redronin/mu-server#32]

**Comment by danielflower** [comment]
Hello, can you just give a bit more context? Just to confirm, the cookie spec says it _should_ be `max-age` so I guess you are saying mu-server is incorrectly setting it as `maxAge`?

One thing I've noticed looking at https://muserver.io/model/cookie?action=create is that the `set-cookie` header uses `Max-Age` which looks correctly to me. But on the response text it prints `maxAge`. This is just because `Cookie.toString()` is printing it as `maxAge`. But when you use `response.addCookie` it does set it correctly on the response header. Note: source code here: https://github.com/3redronin/mu-server-docs/blob/master/src/main/java/io/muserver/docs/samples/CookieExampleHandler.java

Let me know if I've misunderstood something, or if there is some place where it's getting set incorrectly.

**Comment by Przemek0** [comment]
Hello, I use it in different way. I build response from `javax.ws.rs.core` and when I add it to `Response.cookie()` it looks like result of `Cookie.toString()`. I have noticed, what you had said, later that day. I have expected that `Cookie.toString()` will looks like proper header and I've assumed this was mistake. Thank you for your answer and have a nice day.

**Comment by danielflower** [comment]
Just for the record, if setting it like this in a JAX-RS method it uses `max-age=360` in the `set-cookie` header:

```java
NewCookie cookie = new NewCookie("Something", "123456", "/", null, "some comment", 360, false);
return javax.ws.rs.core.Response.noContent().cookie(cookie).build();
```
