### ISSUE TITLE
.withRequestTimeout() is not working properly under HTTP/1.1

### ISSUE THREAD

**Issue by jaylu** [3redronin/mu-server#39]
This can be reproduced in test 

MuServerTest.idleTimeoutCanBeConfiguredAnd408ReturnedIfRequestUploadIsSlow() would failed when turn on http/1.1

in NettyRequestAdapter.readBodyAsString(), the timeout is not measured correctly. 

```java
    public String readBodyAsString() throws IOException {
        if (headers.hasBody()) {
            RequestBodyReader.StringRequestBodyReader reader = createStringRequestBodyReader(maxRequestBytes(), headers());
            claimingBodyRead(reader);
            reader.blockUntilFullyRead();
            return reader.body();
        } else {
            return "";
        }
    }
```

What is the correct behavious for request timeout happened ?  ( withRequestTimeout() )

1. http client would received 408. ( some browser retry the request automatically on receiving 408 ) 
2. on muserver handler, method like request.readBodyAsString() will throw exception.

@danielflower , any comments ?

**Comment by danielflower** [comment]
Weird that it has stopped working. So for `readBodyAsString()` specifically I would say it should:

* Return a 408 if no response headers were sent already, otherwise kill the connection (in http1) or the stream (in h2) if response headers were already sent
* `readBodyAsString()` should throw an exception - some kind of timeout exception

**Comment by danielflower** [comment]
This was due to the test - it set a timeout for, say, 50ms on the server, and then slept for 80ms in the request body sender. In theory this should cause a timeout, but I guess sometimes it doesn't. Bumped to 200ms in the request body sender and the test works (for now). It doesn't test that a timeout exception is returned though. Maybe it should.

**Comment by jaylu** [comment]
master test pass now, closing it.
